/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface License {
  'maxAccounts' : bigint,
  'status' : LicenseStatus,
  'expiryDate' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'productId' : bigint,
  'platform' : string,
  'orderId' : bigint,
  'licenseKey' : string,
  'accountNumbers' : Array<string>,
}
export type LicenseStatus = { 'Active' : null } |
  { 'Revoked' : null } |
  { 'Expired' : null };
export interface Order {
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'productId' : bigint,
  'licenseId' : [] | [bigint],
  'paymentHash' : string,
  'amount' : number,
  'cryptoCoin' : string,
}
export type OrderStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Product {
  'features' : Array<string>,
  'name' : string,
  'tier' : string,
  'description' : string,
  'platform' : string,
  'isActive' : boolean,
  'price' : number,
  'fileUrl' : [] | [ExternalBlob],
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveOrder' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[bigint, number, string, string], bigint>,
  'createProduct' : ActorMethod<[Product], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<[bigint, Order]>>,
  'getAllProducts' : ActorMethod<[], Array<[bigint, Product]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyLicenses' : ActorMethod<[], Array<[bigint, License]>>,
  'getMyOrders' : ActorMethod<[], Array<[bigint, Order]>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectOrder' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'validateLicense' : ActorMethod<
    [string, string],
    [] | [
      { 'status' : LicenseStatus, 'expiryDate' : bigint, 'platform' : string }
    ]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];