/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Float64,
  'fileUrl' : IDL.Opt(ExternalBlob),
});
export const OrderStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'licenseId' : IDL.Opt(IDL.Nat),
  'paymentHash' : IDL.Text,
  'amount' : IDL.Float64,
  'cryptoCoin' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const LicenseStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Revoked' : IDL.Null,
  'Expired' : IDL.Null,
});
export const License = IDL.Record({
  'maxAccounts' : IDL.Nat,
  'status' : LicenseStatus,
  'expiryDate' : IDL.Int,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'platform' : IDL.Text,
  'orderId' : IDL.Nat,
  'licenseKey' : IDL.Text,
  'accountNumbers' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveOrder' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createProduct' : IDL.Func([Product], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
      ['query'],
    ),
  'getAllProducts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyLicenses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, License))],
      ['query'],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Order))], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectOrder' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'validateLicense' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'status' : LicenseStatus,
            'expiryDate' : IDL.Int,
            'platform' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Float64,
    'fileUrl' : IDL.Opt(ExternalBlob),
  });
  const OrderStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'licenseId' : IDL.Opt(IDL.Nat),
    'paymentHash' : IDL.Text,
    'amount' : IDL.Float64,
    'cryptoCoin' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const LicenseStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Revoked' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const License = IDL.Record({
    'maxAccounts' : IDL.Nat,
    'status' : LicenseStatus,
    'expiryDate' : IDL.Int,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'platform' : IDL.Text,
    'orderId' : IDL.Nat,
    'licenseKey' : IDL.Text,
    'accountNumbers' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveOrder' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProduct' : IDL.Func([Product], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getAllProducts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyLicenses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, License))],
        ['query'],
      ),
    'getMyOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectOrder' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'validateLicense' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'status' : LicenseStatus,
              'expiryDate' : IDL.Int,
              'platform' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };